name: CMake CI for Tape-Sorter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake g++ libgtest-dev
        cd /usr/src/gtest
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make

    - name: Create config.json
      run: |
        echo '{
          "read_delay_ms": 0,
          "write_delay_ms": 0,
          "move_delay_ms": 0,
          "rewind_delay_ms": 0
        }' > config.json

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
